logging:
  level: INFO
  loggers:
    uk.gov.ida: INFO

redisUrl: "redis://localhost:4567"
samlEngineUrl: "http://localhost:50120"
configUrl: "http://localhost:50240"
samlSoapProxyUrl: "http://localhost:50160"
